---
# Configure overcloud hosts to use an HTTP/HTTPS proxy server
# In this example the proxy server is hosted by seed-vm.
# A single HTTP proxy URL provides service for both HTTP and HTTPS.

# Note: with the values written to /etc/environment the config
#       applied to bashrc could potentially be skipped.

- name: Configure bashrc HTTP proxy env variables
  hosts: overcloud
  tags:
    - proxy
  vars:
    http_proxy: "http://{{ provision_oc_net_name | net_ip('seed-vm')}}:3128"
    no_proxy: "127.0.0.1,{{ internal_net_vip_address }},{{ internal_net_name | net_ip }}"
  tasks:
    - name: Write http_proxy parameters to bashrc file
      lineinfile:
        path: "{{ ansible_user_dir }}/.bashrc"
        create: yes
        mode: 0755
        state: present
        regexp: "^export {{ item }}=.*"
        line: "export {{ item }}={{ http_proxy }}"
      with_items:
        - http_proxy
        - https_proxy

    - name: Write http_proxy parameters to bashrc file for root user
      lineinfile:
        path: "/root/.bashrc"
        create: yes
        mode: 0755
        state: present
        regexp: "^export {{ item }}=.*"
        line: "export {{ item }}={{ http_proxy }}"
      with_items:
        - http_proxy
        - https_proxy
      become: true

    - name: Write http/s_proxy parameters to /etc/environment
      lineinfile:
        path: "/etc/environment"
        create: yes
        mode: 0755
        state: present
        regexp: "{{ item }}=.*"
        line: "{{ item }}={{ http_proxy }}"
      with_items:
        - http_proxy
        - https_proxy
      become: true

    - name: Write no_proxy parameters to /etc/environment
      lineinfile:
        path: "/etc/environment"
        create: yes
        mode: 0755
        state: present
        regexp: "no_proxy=.*"
        line: "no_proxy={{ no_proxy }}"
      become: true

...
