---
# Setup of VF-LAG systemd configuration.
# This playbook does not setup SR-IOV (perhaps it should) - see stackhpc.sriov
# This playbook should execute after kayobe overcloud host configure has completed.

- name: Prepare hosts for VF-LAG support
  hosts: compute-sriov
  tags:
    - vflag
  tasks:
    # /etc/sysconfig is a RedHat convention - create equivalent here
    - name: create /etc/sysconfig for Ubuntu
      become: true
      file:
        path: /etc/sysconfig
        owner: "root"
        group: "root"
        mode: 0755
        state: directory
      when: ansible_os_family == "Debian"

    # Write /etc/sysconfig/sriov configuration to match this host
    - name: Define parameters in /etc/sysconfig/sriov
      template:
        src: "sysconfig-sriov.j2"
        dest: "/etc/sysconfig/sriov"
        owner: "root"
        group: "root"
        mode: 0755
      become: true
      notify: Reboot and wait

    - name: Transfer VF-LAG helper scripts to /usr/local/bin
      copy:
        src: "{{ item }}"
        dest: "/usr/local/bin/{{ item }}"
        owner: "root"
        group: "root"
        mode: 0755
      become: true
      with_items:
        - "mlnx-vflag-early"
        - "mlnx-vflag-final"
      notify: Reboot and wait

    - name: Transfer VF-LAG systemd units to /etc/systemd/system
      template:
        src: "{{ item }}.j2"
        dest: "/etc/systemd/system/{{ item }}"
        owner: "root"
        group: "root"
        mode: 0644
      become: true
      with_items:
        - "mlnx-vflag-early.service"
        - "mlnx-vflag-final.service"
      notify: Reboot and wait

    - name: Enable VF-LAG systemd units
      systemd:
        daemon_reload: true
        name: "{{ item }}"
        enabled: true
      become: true
      with_items:
        - "mlnx-vflag-early.service"
        - "mlnx-vflag-final.service"
      notify: Reboot and wait

    # There appears to be an issue where the reciprocal symlink from a
    # WantedBy= to a Wants= doesn't get created.  Explicitly ensure it exists.
    - name: Ensure the .wants symlink exists (Ubuntu)
      block:
        - file:
            path: "/etc/systemd/system/systemd-networkd.service.wants"
            state: "directory"
        - file:
            path: "/etc/systemd/system/systemd-networkd.service.wants/mlnx-vflag-early.service"
            src: "/etc/systemd/system/mlnx-vflag-early.service"
            state: "link"
      become: true
      when: ansible_os_family == "Debian"

  handlers:
    - name: Reboot and wait
      include_tasks: tasks/reboot.yml
      tags: reboot
