---
# Certificates generation
- hosts: localhost
  vars_files:
    - "{{ playbook_dir }}/vars/wazuh-single.yml"
    - "{{ playbook_dir }}/vars/wazuh-secrets.yml"
  roles:
    - role: "{{ playbook_dir }}/roles/wazuh-ansible/wazuh-ansible/roles/wazuh/wazuh-indexer"
      perform_installation: false
  become: no
  #become_user: root
  tags:
    - generate-certs
# Single node
- hosts: wazuh-master
  vars_files:
     - "{{ playbook_dir }}/vars/wazuh-single.yml"
  become: yes
  become_user: root
  roles:
    - role: "{{ playbook_dir }}/roles/wazuh-ansible/wazuh-ansible/roles/wazuh/wazuh-indexer"
    - role: "{{ playbook_dir }}/roles/wazuh-ansible/wazuh-ansible/roles/wazuh/ansible-wazuh-manager"
    - role: "{{ playbook_dir }}/roles/wazuh-ansible/wazuh-ansible/roles/wazuh/ansible-filebeat-oss"
    - role: "{{ playbook_dir }}/roles/wazuh-ansible/wazuh-ansible/roles/wazuh/wazuh-dashboard"  
  post_tasks:
    - name: Set http/s_proxy vars in ossec-init.conf for vulnerability detector
      blockinfile:
        path: "/var/ossec/etc/ossec.conf"
        state: present
        owner: root
        group: ossec
        block: |
          HTTPS_PROXY={{ http_proxy_url }}
          HTTP_PROXY={{ http_proxy_url }}
        backup: yes
      when: http_proxy_url is defined
      notify:
        - Restart wazuh
  handlers:
    - name: Restart wazuh
      service:
        name: wazuh-manager
        state: restarted

